name: Weekly Dependency Check

on:
  schedule:
    - cron: '24 0 * * 4' # Runs at 00:24 on Thursday
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.DEPENDENCY_CHECK_TOKEN }}

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run updateDependencies.ps1
        run: .github/resources/updateDependencies.ps1
        shell: pwsh