name: "Filter Changes"

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      functionApp:
        description: "Whether the FunctionApp directory has changed"
        value: ${{ jobs.changes.outputs.functionApp }}

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      functionApp: ${{ steps.filter.outputs.functionApp }}
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        
      - name: filter
        id: filter
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        with:
          filters: |
            functionApp:
              - 'FunctionApp/**'
              - '.github/actions/java-build/action.yml'
              - '.github/workflows/codeql.yml'
              - '.github/workflows/filter-changes.yml'
              - '.github/workflows/maven.yml'