name: "Filter Changes"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      functionApp: ${{ steps.filter.outputs.functionApp }}
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        
      - name: filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            functionApp:
              - 'FunctionApp/**'