name: Azure Function App Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: restpdfformfiller # set this to your function app name on Azure
  PACKAGE_DIRECTORY: 'FunctionApp' # set this to the directory which contains pom.xml file

jobs:
  changes:
    uses: ./.github/workflows/filter-changes.yml

  build:
    needs: changes
    if: ${{ github.event_name == 'workflow_dispatch' || needs.changes.outputs.function-app == 'true' }}
    uses: ./.github/workflows/maven.yml

  deploy-and-submit-dependencies:
    needs: build
    if: ${{ success() }}
    runs-on: windows-latest
    steps:
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'restpdfformfiller'
          slot-name: 'dev'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2809551214454B81BB4D28673CCAEE70 }}
          package: '.'
          respect-pom-xml: true
        # Generate GitHub Maven Dependency Tree
        # https://github.com/marketplace/actions/maven-dependency-tree-dependency-submission
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
        with:
          directory: './${{ env.PACKAGE_DIRECTORY }}'