# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

env:
  PACKAGE_DIRECTORY: 'FunctionApp' # set this to the directory which contains pom.xml file
  JAVA_VERSION: '17' # set this to the java version to use

jobs:
  
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: 'Restore Project Dependencies Using Mvn'
        shell: pwsh
        run: |
          pushd './${{ env.PACKAGE_DIRECTORY }}'
          mvn clean package
          popd

      - name: Build with Maven
        run: mvn -B package --file ${{ env.PACKAGE_DIRECTORY }}/pom.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: RestPdfFormFiller-0.1.0.jar
          path: 'FunctionApp/target/azure-functions/RestPdfFormFiller-1654224697708/RestPdfFormFiller-0.1.0.jar'